### PR TITLE
Announce 3.6.0 and update theme

### PR DESCRIPTION
**Pull request by QuLogic**
And update to 3.6.0 theme.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, same problem as #52.

**Comment by QuLogic** [comment]
Ah, I messed up the logo link due to copy&paste, I think.

**Comment by QuLogic** [comment]
Pushed an update so it matches the previous links.

**Comment by QuLogic** [comment]
Pushed an additional fix for the search button not popping up. I think pydata-sphinx-theme has better support for landing pages, so we should investigate if we can remove our custom template override sometime in the future.

**Review by timhoffm — APPROVED** [review]

**Comment by jklymak** [comment]
This actually looks _really_ bad if the wrapping happens on my machine:

FrontpageIssue

**Pull request merged**
