### PR TITLE
MNT: Update Matplotlib and pydata sphinx theme

### PR DESCRIPTION
**Pull request by QuLogic**
I didn't test, so we'll see how the build goes.

### CODE REVIEW

**Comment by QuLogic** [comment]
OK, managed to get it building; however there are some differences in the result:
- Links are now underlined:
    - The header links are underlined on hover.
    - Body links are always underlined.
- The social links are different:
    - slightly smaller in the header, and
    - gone in the footer.
- The primary highlight colour seems to be misconfigured:
    - The header links are purple on hover instead of blue.
    - The main heading is not blue any more.
    - The body text link hover colour is purple instead of orange.
    - The Try on Binder button is purple on hover instead of white.
    - The quicklinks are black on hover for Reference and Documentation, but purple for the others
    - Some footer links are blue instead of white (without hover).
- The header links are centred.
- There's a slight change in spacing between Stable and Development links in the footer.

**Comment by timhoffm** [comment]
Since we‘re based on pydata-sphinx-theme, we should follow most of their design decisions. The more we customize, the more we have maintenance on future updates. For example, the underlying is a conscious accessibility decision. Additionally, the same changes apply to our main docs, and we want consistency between them.

We should simply accept most of the changes. The only things to watch out for are css changes on their side that affect custom elements on our side in a negative way ( parts of the primary highlight color).

**Review by melissawm — COMMENTED** [review]
Hi folks - passing by :smile:

One thing to consider is that the landing page will look different from the rest of the docs with the customizations (in fact, it already does. For example, link highlights on hover are in orange for the landing page but purple for the rest of the pages).

For the other things, a couple of changes to the `landing.css` file should fix most of it. I am happy to push a commit here if that's easier. I also recommend adding
```
html_theme_options = {
    "back_to_top_button": False,
}
```

to conf.py to turn off the back to top button in the landing pages. Cheers!

**Comment by QuLogic** [comment]
So I think I actually misunderstood some of the style; I thought we had set blue/orange for links to follow our default colour cycle, but it turns out that was just the default from `pydata-sphinx-theme`. So the change to purple-on-hover should be expected, and is consistent with our latest doc builds.

>       * The quicklinks are black on hover for Reference and Documentation, but purple for the others

These were because colours were set on `a` but not `a:visited`, and formerly, it seems that those were inherited; fixed [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-30d5575d441b6281f9449897ee3650c372f06d62f54cbc018a6f4c5da917dbc4R173-R174).

>       * Some footer links are blue instead of white (without hover).

Same to above; fixed [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-30d5575d441b6281f9449897ee3650c372f06d62f54cbc018a6f4c5da917dbc4R389-R401).

>       * The Try on Binder button is purple on hover instead of white.

Similarly, this is because the theme/Sphinx started setting colour on `a:hover` instead of inheriting it, so we need to also override that ourselves.

Did that [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-30d5575d441b6281f9449897ee3650c372f06d62f54cbc018a6f4c5da917dbc4R678-R681) and [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-30d5575d441b6281f9449897ee3650c372f06d62f54cbc018a6f4c5da917dbc4R703-R704).

>     * There's a slight change in spacing between Stable and Development links in the footer.

Fixed [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-30d5575d441b6281f9449897ee3650c372f06d62f54cbc018a6f4c5da917dbc4R407-R412) plus [here](https://github.com/matplotlib/mpl-brochure-site/pull/92/files#diff-82327118a8b0a069cb8a1a6c3a2d7d6eb7fe19e62f8ecaa11a4cbe35b58c08a0R65-R67).

> I also recommend adding
> 
> ```
> html_theme_options = {
>     "back_to_top_button": False,
> }
> ```
> 
> to conf.py to turn off the back to top button in the landing pages. Cheers!

Done.

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
