### PR TITLE
Fix dark mode

### PR DESCRIPTION
**Pull request by QuLogic**
This fixes a few things when dark mode is enabled.

- Use theme colours for borders, callout icons, and link-like things, which were formerly hard-coded blue and too dark.
- Re-create the quicklink icons in Inkscape so that they could have a transparent background. I added a slight white border for contrast.
- Disable the darkening filter from pydata-sphinx-theme on these images which are meant to work in dark mode. This is a backport of pydata/pydata-sphinx-theme#914 and pydata/pydata-sphinx-theme#942.
- Flip the footer gradient in dark mode to preserve the contrast between body and footer.

The plot type images still have the filter from the theme.  I don't know if we should turn that off as well, or add a new style for dark mode.

### CODE REVIEW

**Comment by timhoffm** [comment]
> can that slight white border be a slight gray border? It kinda hurts my eyes

That could be achieved with a semi-transparent white border. I think We don't want grey for the light case.

**Comment by QuLogic** [comment]
How does 75% look? (haven't done the documentation one yet since that's a plot)
image

**Comment by timhoffm** [comment]
LGTM. Let‘s try.

**Comment by timhoffm** [comment]
AFAICS, the 75% change must still be committed.

**Comment by QuLogic** [comment]
Yes sorry, should be in now.

**Comment by timhoffm** [comment]
> Maybe also apply to the inner white to make the icons less glaring overall.

What I meant is also making the inner white area (marked red) partly transparaent:

grafik

You can dismiss if you don't want to, but I'm not sure I made my proposal clear.

**Comment by QuLogic** [comment]
I tried 75% everywhere, but it looks a bit too dark IMO:
Screenshot 2022-09-27 at 05-46-07 Matplotlib — Visualization with Python
Here are increasing levels of transparency from 80% to 100% in 5% increments across the icons:
Screenshot 2022-09-27 at 05-46-41 Matplotlib — Visualization with Python
I think maybe 90-95% is fine?

**Comment by QuLogic** [comment]
OK, moved to 90%, and actually fixed the documentation one directly in the script, so it's actually transparent.

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
