### PR TITLE
MNT: update conf

### PR DESCRIPTION
**Pull request by jklymak**
The brochure site doesn't build on recent pydata-sphinx-theme....

### CODE REVIEW

**Comment by jklymak** [comment]
There is a build error for some reason, that I don't get at home, but the build looks OK?

**Comment by QuLogic** [comment]
It's because we seem to have an old version of `pygments` already installed, which doesn't get upgraded; https://github.com/pydata/pydata-sphinx-theme/pull/778

We could put in a minimum version here to get it working.

**Comment by jklymak** [comment]
Cool.  Feel free to push onto this pr if you like.  (Bedtime here)

**Comment by QuLogic** [comment]
Note that this adds in the dark mode switcher, due to switching to the latest mpl-sphinx-theme/pydata-sphinx-theme.

This nearly works, except for:
* The icons in the first section that still have a white background. I think we can easily regenerate them with a dark background, but I'm not sure how good they would look.
* The footer looks a bit odd; maybe just inverting the gradient would work here?
* Some of the frames may be a tad bit strong.

Unlike the devdocs, merging this here will deploy immediately, so I'm not sure if we want to do that without looking in to these items.

**Comment by timhoffm** [comment]
We should merge this together with the next release. Adding the theme Switcher should be synced between brochure and docs.

**Comment by jklymak** [comment]
Yes, for now we should pin pydata-sphinx-theme <0.9.0 I think....

**Pull request closed without merging**
